//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrmFindJobSerivces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        public string company_name { get; set; }
        public string address { get; set; }
        public string gmail { get; set; }
        public string phone { get; set; }
        public string image { get; set; }
    }
}
