//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrmFindJobSerivces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class skill
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> point { get; set; }
        public string gmail { get; set; }
        public Nullable<int> job_id { get; set; }
        public string image { get; set; }
    }
}
